
POST http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correoElectronico": "1@gmail.com",
    "contrasena": "1"
}

###

POST http://localhost:3000/api/clases
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoicyIsImlzcyI6IlVWZW15U2Vydmlkb3JKV1QiLCJhdWQiOiJVc3Vhcmlvc1VWZW15SldUIiwiaWF0IjoxNzE1NjY0NDAwLCJleHAiOjE3MTU2NjU2MDB9.jU_km6ouz1uTJMUUPEIoLSk4iINWmIXe95_iYSJp7l8

###

POST http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correoElectronico": "ejemplo@gmail.com",
    "contrasena": "hola"
}

###

POST http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correoElectronico": "",
    "contrasena": ""
}