
POST http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correoElectronico": "sulem477@gmail.com",
    "contrasena": "1"
}

###

POST http://localhost:3000/api/clases
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3ByaW1hcnlzaWQiOjEsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1bGVtNDc3QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6InMiLCJpc3MiOiJVVmVteVNlcnZpZG9ySldUIiwiYXVkIjoiVXN1YXJpb3NVVmVteUpXVCIsImlhdCI6MTcxNTgxOTYzMCwiZXhwIjoxNzE1ODIwODMwfQ.5rpd_7Fw59hoD4CJtiT_GCxgaM9Xfj3354rl8lzu7Ak
Content-Type: application/json

{
    "idCurso": 1,
    "nombre": "Clase con documentos",
    "descripcion": "cverdaderamente",
    "documentos": [
        {
            "nombre": "a",
            "archivo": ""
        }
    ]
}

###

POST http://localhost:3000/api/documentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3ByaW1hcnlzaWQiOjEsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1bGVtNDc3QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6InMiLCJpc3MiOiJVVmVteVNlcnZpZG9ySldUIiwiYXVkIjoiVXN1YXJpb3NVVmVteUpXVCIsImlhdCI6MTcxNTgyOTk2NywiZXhwIjoxNzE1ODMxMTY3fQ.2dWmvdhRKlXGhWOx63CKl-8vqtNoujmKTbswmNsvZjs
Content-Type: application/json

{
    "idClase": 1,
    "nombre": "Documentos",
    "archivo": ""
}

###

POST http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correoElectronico": "ejemplo@gmail.com",
    "contrasena": "hola"
}

###

POST http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correoElectronico": "",
    "contrasena": ""
}