###

POST http://localhost:3000/api/documentos
Content-Type: multipart/form-data; boundary=XXX
Authorization: Bearer {{ token }}

--XXX
Content-Disposition: form-data; name="file"; filename="elpadrino.jpg"
Content-Type: image/jpeg

< ./assets/elpadrino.jpg
--XXX--

###

PUT http://localhost:3000/api/clases/59
Content-Type: application/json

{
    "idClase": "59",
    "nombre": "Modificadors de acceso",
    "descripcion": "En esta clase se verán modificadores de acceso"
}

###

GET http://localhost:3000/api/clases/140
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3ByaW1hcnlzaWQiOjEsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im1lbHVzQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6InMiLCJpc3MiOiJVVmVteVNlcnZpZG9ySldUIiwiYXVkIjoiVXN1YXJpb3NVVmVteUpXVCIsImlhdCI6MTcxODIwODY0NCwiZXhwIjoxNzE4MjgxODQ0fQ.8FfysvWaenfXMlNOfQyaf8pX4krwNerxiRFs7Fr5UOQ


###

GET http://localhost:3000/api/clases/curso/213






###
DELETE http://localhost:3000/api/clases/38
