GET http://localhost:3000/api/cursos

###

GET http://localhost:3000/api/cursos/16

###

POST http://localhost:3000/api/cursos
Content-Type: application/json

{
    "titulo": "Curso de prueba",
    "descripcion": "Curso de prueba",
    "objetivos": "Curso de prueba",
    "requisitos": "Curso de prueba",
    "idUsuario": 1
}

###

PUT http://localhost:3000/api/cursos/42
Content-Type: application/json

{
    "titulo": "Curso de prueba",
    "descripcion": "Curso de prueba",
    "objetivos": "Curso de prueba",
    "requisitos": "Curso de prueba2",
    "idUsuario": 1
}

### TO DO Borrar los cursos usuarios, ya borra las etiquetas

DELETE http://localhost:3000/api/cursos/36