GET http://localhost:3000/api/cursosetiquetas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3ByaW1hcnlzaWQiOjIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1bGVtNDc3QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Implc3VzIiwiaXNzIjoiVVZlbXlTZXJ2aWRvckpXVCIsImF1ZCI6IlVzdWFyaW9zVVZlbXlKV1QiLCJpYXQiOjE3MTU5MDQ5NjUsImV4cCI6MTcxNTkwNjE2NX0.BRM8gQ6PFb2mTMrDJYltMCd6hEeEoZUnXHgC-Xc1g8I


###

GET http://localhost:3000/api/cursosetiquetas/11

###

POST http://localhost:3000/api/cursosetiquetas
Content-Type: application/json

{
    "idCurso": 31,
    "idEtiqueta": 1
}

###

PUT http://localhost:3000/api/cursosetiquetas/10
Content-Type: application/json

{
    "idCurso": 16,
    "idEtiqueta": 4
}

###

DELETE http://localhost:3000/api/cursosetiquetas/19


