GET http://localhost:3000/api/usuarios

###

GET http://localhost:3000/api/usuarios/2

###

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "idUsuario": 1,
    "nombres": "Usuario de prueba",
    "apellidos": "Usuario de prueba",
    "correoElectronico": "usuarioprueba@gmail.com",
    "contrasena": "$2a$12$eHNlLAWFcvmfeZG93A/HxOsHfhB/01gfa1MkPfKSnuSSt1Y02T8zq"
}

###

PUT http://localhost:3000/api/usuarios/2
Content-Type: application/json

{
    "nombres": "Usuario de pruebaNuevo",
    "apellidos": "Usuario de pruebaNuevo",
    "correoElectronico": "1",
    "contrasena": "$2a$12$eHNlLAWFcvmfeZG93A/HxOsHfhB/01gfa1MkPfKSnuSSt1Y02T8zq"
}

###

DELETE http://localhost:3000/api/usuarios/2